feat: Allow to set EVENT_TRACKING_BACKEND and XAPI_EVENTS_ENABLED
eduNEXT/configuration pull request #14
Opened 2022-09-29 20:25 UTC by andrey-canon

## Description 
Allow to write EVENT_TRACKING_BACKENDS settings and XAPI_EVENTS_ENABLED value

2022-09-30 00:22 UTC, johanv26 approved these changes

2022-09-30 00:28 UTC, johanv26 commented
Why is it necessary to change the configuration if you are only configuring settings? Because this xapi config doesn't add or make something with different roles or playbooks.
Maybe the configuration could be loaded here 
https://github.com/nelc/configuration-secure/blob/master/vars-stage.yml#L187
What do you think  ? @andrey-canon

2022-09-30 00:28 UTC, johanv26 requested changes
https://github.com/eduNEXT/configuration/pull/14#issuecomment-1262965989

2022-10-05 22:05 UTC, andrey-canon commented
> Why is it necessary to change the configuration if you are only configuring settings? Because this xapi config doesn't add or make something with different roles or playbooks. Maybe the configuration could be loaded here https://github.com/nelc/configuration-secure/blob/master/vars-stage.yml#L187 What do you think ? @andrey-canon

Thanks for the suggestion, I close this pr since the setting work inside env_extra

2022-10-05 22:05 UTC, closed without merging